CREATE TABLE  "AERODYNAMICS_PROJECT" 
   (	"COMPONENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMPONENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"TIMES_USED" NUMBER(20,0) NOT NULL ENABLE, 
	"REMAINING" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "AERODYNAMICS_PROJECT_CON" UNIQUE ("COMPONENT_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "AERODYNAMICS_PROJECT" ADD CONSTRAINT "AERODYNAMICS_PROJECT_FK" FOREIGN KEY ("COMPONENT_ID")
	  REFERENCES  "COMPONENTS_PROJECT" ("COMPONENT_ID") ENABLE

CREATE TABLE  "CAR_PROJECT" 
   (	"CAR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DRIVER_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DRIVER_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "CAR_PROJECT_PK" PRIMARY KEY ("CAR_ID")
  USING INDEX  ENABLE
   )

CREATE TABLE  "CHASSIS_PROJECT" 
   (	"COMPONENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMPONENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"TIMES_USED" NUMBER(20,0) NOT NULL ENABLE, 
	"REMAINING" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "CHASSIS_PROJECT_UNIQUE" UNIQUE ("COMPONENT_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "CHASSIS_PROJECT" ADD CONSTRAINT "CHASSIS_PROJECT_FK" FOREIGN KEY ("COMPONENT_ID")
	  REFERENCES  "COMPONENTS_PROJECT" ("COMPONENT_ID") ENABLE

CREATE TABLE  "COMPONENTS_PROJECT" 
   (	"COMPONENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMPONENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"DEPT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"CAR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"FACTORY_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"FACTORY_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "COMPONENTS_PROJECT_PK" PRIMARY KEY ("COMPONENT_ID", "COMPONENT_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "COMPONENTS_PROJECT_UNIQUE1" UNIQUE ("COMPONENT_ID", "DEPT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "COMPONENTS_PROJECT_UNIQUE2" UNIQUE ("CAR_ID", "FACTORY_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "COMPONENTS_PROJECT_UNIQUE3" UNIQUE ("COMPONENT_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "COMPONENTS_PROJECT" ADD CONSTRAINT "COMPONENTS_PROJECT_FK1" FOREIGN KEY ("DEPT_ID")
	  REFERENCES  "DEPARTMENTS_PROJECT" ("DEPT_ID") ENABLE

ALTER TABLE  "COMPONENTS_PROJECT" ADD CONSTRAINT "COMPONENTS_PROJECT_FK2" FOREIGN KEY ("CAR_ID")
	  REFERENCES  "CAR_PROJECT" ("CAR_ID") ENABLE

ALTER TABLE  "COMPONENTS_PROJECT" ADD CONSTRAINT "COMPONENTS_PROJECT_FK3" FOREIGN KEY ("FACTORY_ID")
	  REFERENCES  "FACTORIES_PROJECT" ("FACTORY_ID") ENABLE

CREATE TABLE  "DEPARTMENTS_PROJECT" 
   (	"DEPT_ID" NUMBER(20,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	 CONSTRAINT "DEPARTMENTS_PROJECT_PK" PRIMARY KEY ("DEPT_ID", "DEPT_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DEPARTMENTS_PROJECT_UNIQUE" UNIQUE ("DEPT_ID")
  USING INDEX  ENABLE
   )

CREATE TABLE  "DRIVER_PROJECT" 
   (	"DRIVER_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DRIVER_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"DRIVER_ROLE" VARCHAR2(20) NOT NULL ENABLE, 
	"CAR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "DRIVER_PROJECT_PK" PRIMARY KEY ("DRIVER_ID", "DRIVER_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DRIVER_PROJECT_UNIQUE" UNIQUE ("DRIVER_ID", "CAR_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "DRIVER_PROJECT" ADD CONSTRAINT "DRIVER_PROJECT_FK" FOREIGN KEY ("CAR_ID")
	  REFERENCES  "CAR_PROJECT" ("CAR_ID") ENABLE

CREATE TABLE  "ENGINEERS_PROJECT" 
   (	"ENG_ID" NUMBER(20,0), 
	"ENG_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"DEPT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"CAR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ENG_PHONE_NO" VARCHAR2(20) NOT NULL ENABLE, 
	"ENG_ADDRESS" VARCHAR2(20) NOT NULL ENABLE, 
	"HEAD_ENG_ID" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "ENGINEERS_PROJECT_PK" PRIMARY KEY ("ENG_ID", "ENG_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ENGINEERS_PROJECT_UNIQUE1" UNIQUE ("ENG_ID", "DEPT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ENGINEERS_PROJECT_UNIQUE2" UNIQUE ("CAR_ID", "HEAD_ENG_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "ENGINEERS_PROJECT" ADD CONSTRAINT "ENGINEERS_PROJECT_FK1" FOREIGN KEY ("DEPT_ID")
	  REFERENCES  "DEPARTMENTS_PROJECT" ("DEPT_ID") ENABLE

ALTER TABLE  "ENGINEERS_PROJECT" ADD CONSTRAINT "ENGINEERS_PROJECT_FK2" FOREIGN KEY ("CAR_ID")
	  REFERENCES  "CAR_PROJECT" ("CAR_ID") ENABLE

ALTER TABLE  "ENGINEERS_PROJECT" ADD CONSTRAINT "ENGINEERS_PROJECT_FK3" FOREIGN KEY ("HEAD_ENG_ID")
	  REFERENCES  "HEAD_ENGINEER_PROJECT" ("HEAD_ENG_ID") ENABLE

CREATE TABLE  "EQUIPMENT_PROJECT" 
   (	"EQUIPMENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"EQUIPMENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"DEPT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"FACTORY_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"FACTORY_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "EQUIPMENT_PROJECT_PK" PRIMARY KEY ("EQUIPMENT_ID", "EQUIPMENT_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EQUIPMENT_PROJECT_UNIQUE" UNIQUE ("EQUIPMENT_ID", "DEPT_ID", "FACTORY_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EQUIPMENT_PROJECT_UNIQUE2" UNIQUE ("EQUIPMENT_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "EQUIPMENT_PROJECT" ADD CONSTRAINT "EQUIPMENT_PROJECT_FK1" FOREIGN KEY ("DEPT_ID")
	  REFERENCES  "DEPARTMENTS_PROJECT" ("DEPT_ID") ENABLE

ALTER TABLE  "EQUIPMENT_PROJECT" ADD CONSTRAINT "EQUIPMENT_PROJECT_FK2" FOREIGN KEY ("FACTORY_ID")
	  REFERENCES  "FACTORIES_PROJECT" ("FACTORY_ID") ENABLE

CREATE TABLE  "EXPENSES_PROJECT" 
   (	"EXPENSE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"EXPENSE_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"EXPENSE_VALUE" NUMBER(20,0), 
	"DEPT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "EXPENSES_PROJECT_PK" PRIMARY KEY ("EXPENSE_ID", "EXPENSE_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EXPENSES_PROJECT_UNIQUE" UNIQUE ("EXPENSE_ID", "DEPT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EXPENSES_PROJECT_UNIQUE2" UNIQUE ("EXPENSE_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "EXPENSES_PROJECT" ADD CONSTRAINT "EXPENSES_PROJECT_FK" FOREIGN KEY ("DEPT_ID")
	  REFERENCES  "DEPARTMENTS_PROJECT" ("DEPT_ID") ENABLE

CREATE TABLE  "FACTORIES_PROJECT" 
   (	"FACTORY_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"FACTORY_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "FACTORIES_PROJECT_PK" PRIMARY KEY ("FACTORY_ID", "FACTORY_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FACTORIES_PROJECT_UNIQUE" UNIQUE ("FACTORY_ID")
  USING INDEX  ENABLE
   )

CREATE TABLE  "FACTORY_LOCATIONS_PROJECT" 
   (	"FACTORY_ADDRESS" VARCHAR2(200) NOT NULL ENABLE, 
	"FACTORY_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"FACTORY_CITY" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "FACTORY_LOCATIONS_PROJECT_UN" UNIQUE ("FACTORY_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "FACTORY_LOCATIONS_PROJECT" ADD CONSTRAINT "FACTORY_LOCATIONS_PROJECT_FK" FOREIGN KEY ("FACTORY_ID")
	  REFERENCES  "FACTORIES_PROJECT" ("FACTORY_ID") ENABLE

CREATE TABLE  "HEAD_ENGINEER_PROJECT" 
   (	"HEAD_ENG_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"HEAD_ENG_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"DEPT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"HEAD_ENG_PHONE_NO" VARCHAR2(20) NOT NULL ENABLE, 
	"HEAD_ENG_ADDRESS" VARCHAR2(20) NOT NULL ENABLE, 
	"CAR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "HEAD_ENGINEER_PROJECT_PK" PRIMARY KEY ("HEAD_ENG_ID", "HEAD_ENG_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "HEAD_ENGINEER_PROJECT_UNIQUE" UNIQUE ("HEAD_ENG_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "HEAD_ENGINEER_PROJECT" ADD CONSTRAINT "HEAD_ENGINEER_PROJECT_FK1" FOREIGN KEY ("DEPT_ID")
	  REFERENCES  "DEPARTMENTS_PROJECT" ("DEPT_ID") ENABLE

ALTER TABLE  "HEAD_ENGINEER_PROJECT" ADD CONSTRAINT "HEAD_ENGINEER_PROJECT_FK2" FOREIGN KEY ("CAR_ID")
	  REFERENCES  "CAR_PROJECT" ("CAR_ID") ENABLE

CREATE TABLE  "LOGISTICS_PROJECT" 
   (	"COMPONENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMPONENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "LOGISTICS_PROJECT_UNIQUE" UNIQUE ("COMPONENT_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "LOGISTICS_PROJECT" ADD CONSTRAINT "LOGISTICS_PROJECT_FK" FOREIGN KEY ("COMPONENT_ID")
	  REFERENCES  "COMPONENTS_PROJECT" ("COMPONENT_ID") ENABLE

CREATE TABLE  "MARKETING_PROJECT" 
   (	"EXPENSE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"EQUIPMENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"UTILITY" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "MARKETING_PROJECT_CON" UNIQUE ("EXPENSE_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "MARKETING_PROJECT" ADD CONSTRAINT "MARKETING_PROJECT_FK" FOREIGN KEY ("EXPENSE_ID")
	  REFERENCES  "EXPENSES_PROJECT" ("EXPENSE_ID") ENABLE

CREATE TABLE  "PIT_CREW_PROJECT" 
   (	"EQUIPMENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"EQUIPMENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PIT_CREW_PROJECT_UNIQUE" UNIQUE ("EQUIPMENT_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "PIT_CREW_PROJECT" ADD CONSTRAINT "PIT_CREW_PROJECT_FK" FOREIGN KEY ("EQUIPMENT_ID")
	  REFERENCES  "EQUIPMENT_PROJECT" ("EQUIPMENT_ID") ENABLE

CREATE TABLE  "POWERTRAIN_PROJECT" 
   (	"COMPONENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMPONENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"TIMES_USED" NUMBER(20,0) NOT NULL ENABLE, 
	"REMAINING" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "POWERTRAIN_PROJECT_UNIQUE" UNIQUE ("COMPONENT_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "POWERTRAIN_PROJECT" ADD CONSTRAINT "POWERTRAIN_PROJECT_FK" FOREIGN KEY ("COMPONENT_ID")
	  REFERENCES  "COMPONENTS_PROJECT" ("COMPONENT_ID") ENABLE

CREATE TABLE  "RELIABILITY_PROJECT" 
   (	"COMPONENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMPONENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"TIMES_USED" NUMBER(20,0) NOT NULL ENABLE, 
	"REMAINING" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "RELIABILITY_PROJECT_UNIQUE" UNIQUE ("COMPONENT_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "RELIABILITY_PROJECT" ADD CONSTRAINT "RELIABILITY_PROJECT_FK" FOREIGN KEY ("COMPONENT_ID")
	  REFERENCES  "COMPONENTS_PROJECT" ("COMPONENT_ID") ENABLE

CREATE TABLE  "R_AND_D_PROJECT" 
   (	"COMPONENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMPONENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"DEPT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"STATUS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"FACTORY_ID" NUMBER(20,0) NOT NULL ENABLE
   )

ALTER TABLE  "R_AND_D_PROJECT" ADD CONSTRAINT "R_AND_D_PROJECT_FK1" FOREIGN KEY ("COMPONENT_ID")
	  REFERENCES  "COMPONENTS_PROJECT" ("COMPONENT_ID") ENABLE

ALTER TABLE  "R_AND_D_PROJECT" ADD CONSTRAINT "R_AND_D_PROJECT_FK2" FOREIGN KEY ("DEPT_ID")
	  REFERENCES  "DEPARTMENTS_PROJECT" ("DEPT_ID") ENABLE

ALTER TABLE  "R_AND_D_PROJECT" ADD CONSTRAINT "R_AND_D_PROJECT_FK3" FOREIGN KEY ("FACTORY_ID")
	  REFERENCES  "FACTORIES_PROJECT" ("FACTORY_ID") ENABLE

ALTER TABLE  "R_AND_D_PROJECT" ADD CONSTRAINT "R_AND_D_PROJECT_FK4" FOREIGN KEY ("STATUS_ID")
	  REFERENCES  "R_AND_D_STATUS_PROJECT" ("STATUS_ID") ENABLE

CREATE TABLE  "R_AND_D_STATUS_PROJECT" 
   (	"STATUS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"STATUS_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "R_AND_D_STATUS_PROJECT_PK" PRIMARY KEY ("STATUS_ID", "STATUS_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "R_AND_D_STATUS_PROJECT_UNIQUE" UNIQUE ("STATUS_ID")
  USING INDEX  ENABLE
   )

CREATE TABLE  "SIMULATOR_PROJECT" 
   (	"COMPONENT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMPONENT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"TIMES_USED" NUMBER(20,0) NOT NULL ENABLE, 
	"REMAINING" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "SIMULATOR_PROJECT_UNIQUE" UNIQUE ("COMPONENT_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "SIMULATOR_PROJECT" ADD CONSTRAINT "SIMULATOR_PROJECT_FK" FOREIGN KEY ("COMPONENT_ID")
	  REFERENCES  "COMPONENTS_PROJECT" ("COMPONENT_ID") ENABLE

CREATE TABLE  "SPONSORS_PROJECT" 
   (	"SPONSOR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SPONSOR_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"SPONSOR_VALUE" NUMBER(20,0) NOT NULL ENABLE, 
	"EXPENSE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "SPONSORS_PROJECT_PK" PRIMARY KEY ("SPONSOR_ID", "SPONSOR_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SPONSORS_PROJECT_UNIQUE" UNIQUE ("SPONSOR_ID", "EXPENSE_ID")
  USING INDEX  ENABLE
   )

ALTER TABLE  "SPONSORS_PROJECT" ADD CONSTRAINT "SPONSORS_PROJECT_FK" FOREIGN KEY ("EXPENSE_ID")
	  REFERENCES  "EXPENSES_PROJECT" ("EXPENSE_ID") ENABLE